//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.db
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class dbEMPLOYEE_List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbEMPLOYEE_List()
        {
            this.dbDISTRIBUTION_List = new HashSet<dbDISTRIBUTION_List>();
            this.dbTRACKCOLLECTION_List = new HashSet<dbTRACKCOLLECTION_List>();
        }
    
        public int EMPLOYYE_ID { get; set; }

        [Required(ErrorMessage = "Required")]
        public string EMPLOYEE_NAME { get; set; }
        public string REQUESTED_TIME { get; set; }
        public Nullable<int> NGO_ID { get; set; }
        public Nullable<int> RESTAURENT_ID { get; set; }
        public Nullable<int> FOOD_ID { get; set; }

        [Required(ErrorMessage = "Required")]
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbDISTRIBUTION_List> dbDISTRIBUTION_List { get; set; }
        public virtual dbFOODITEM_List dbFOODITEM_List { get; set; }
        public virtual dbNGO_List dbNGO_List { get; set; }
        public virtual dbRESTAURENT_List dbRESTAURENT_List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbTRACKCOLLECTION_List> dbTRACKCOLLECTION_List { get; set; }
    }
}
