//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zero_Hunger.db
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class dbRESTAURENT_List
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dbRESTAURENT_List()
        {
            this.dbDISTRIBUTION_List = new HashSet<dbDISTRIBUTION_List>();
            this.dbEMPLOYEE_List = new HashSet<dbEMPLOYEE_List>();
            this.dbTRACKCOLLECTION_List1 = new HashSet<dbTRACKCOLLECTION_List>();
            this.NGO_RESTAURENT = new HashSet<NGO_RESTAURENT>();
        }
    
        public int RESTAURENT_ID { get; set; }

        [Required(ErrorMessage = "Required")]
        public string RESTAURENT_NAME { get; set; }
        public Nullable<int> COLLECTREQUEST_ID { get; set; }
        public string MAXPRESERVATION_TIME { get; set; }
        public Nullable<int> FOOD_ID { get; set; }

        [Required(ErrorMessage = "Required")]
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbDISTRIBUTION_List> dbDISTRIBUTION_List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbEMPLOYEE_List> dbEMPLOYEE_List { get; set; }
        public virtual dbFOODITEM_List dbFOODITEM_List { get; set; }
        public virtual dbRESTAURENT_List dbRESTAURENT_List1 { get; set; }
        public virtual dbRESTAURENT_List dbRESTAURENT_List2 { get; set; }
        public virtual dbTRACKCOLLECTION_List dbTRACKCOLLECTION_List { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dbTRACKCOLLECTION_List> dbTRACKCOLLECTION_List1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGO_RESTAURENT> NGO_RESTAURENT { get; set; }
    }
}
